# Agent Card for Example White Agent (Subject being evaluated)

name = "ExampleWhiteAgent"
description = """
This is an example white agent that can be evaluated by the terminal-bench green agent.

It serves as a reference implementation showing how to:
- Expose an A2A interface
- Receive task instructions
- Process terminal-bench tasks
- Return results

In a production implementation, this agent would:
- Use an LLM to understand and solve tasks
- Have access to terminal execution tools
- Implement proper error handling
- Track execution state
"""
url = "http://localhost:8001/"
version = "1.0.0"

defaultInputModes = ["text"]
defaultOutputModes = ["text"]

[capabilities]
streaming = true

[[skills]]
id = "terminal_execution"
name = "Terminal Execution"
description = "Executes terminal commands (to be implemented)"
tags = ["terminal", "execution"]

[[skills]]
id = "problem_solving"
name = "Problem Solving"
description = "Solves terminal-bench tasks (to be implemented)"
tags = ["problem-solving", "tasks"]

